{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f38aeb40",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2             # Importing OpenCV library for computer vision tasks\n",
    "import numpy as np      # Importing NumPy for numerical operations\n",
    "import mediapipe as mp  # Importing Mediapipe for hand tracking\n",
    "from collections import deque  # Importing deque from collections to handle drawing points\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "61e6c790",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: opencv-python in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (4.10.0.84)\n",
      "Requirement already satisfied: numpy>=1.21.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from opencv-python) (1.24.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install opencv-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "cf652fbd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: mediapipe in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (0.10.14)\n",
      "Requirement already satisfied: absl-py in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (2.1.0)\n",
      "Requirement already satisfied: attrs>=19.1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from mediapipe) (22.1.0)\n",
      "Requirement already satisfied: flatbuffers>=2.0 in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (24.3.25)\n",
      "Requirement already satisfied: jax in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (0.4.31)\n",
      "Requirement already satisfied: jaxlib in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (0.4.31)\n",
      "Requirement already satisfied: matplotlib in c:\\programdata\\anaconda3\\lib\\site-packages (from mediapipe) (3.7.2)\n",
      "Requirement already satisfied: numpy in c:\\programdata\\anaconda3\\lib\\site-packages (from mediapipe) (1.24.3)\n",
      "Requirement already satisfied: opencv-contrib-python in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (4.10.0.84)\n",
      "Requirement already satisfied: protobuf<5,>=4.25.3 in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (4.25.4)\n",
      "Requirement already satisfied: sounddevice>=0.4.4 in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from mediapipe) (0.5.0)\n",
      "Requirement already satisfied: CFFI>=1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from sounddevice>=0.4.4->mediapipe) (1.15.1)\n",
      "Requirement already satisfied: ml-dtypes>=0.2.0 in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from jax->mediapipe) (0.4.0)\n",
      "Requirement already satisfied: opt-einsum in c:\\users\\admin\\appdata\\roaming\\python\\python311\\site-packages (from jax->mediapipe) (3.3.0)\n",
      "Requirement already satisfied: scipy>=1.10 in c:\\programdata\\anaconda3\\lib\\site-packages (from jax->mediapipe) (1.11.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (1.0.5)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (4.25.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (1.4.4)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (23.1)\n",
      "Requirement already satisfied: pillow>=6.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (9.4.0)\n",
      "Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (3.0.9)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->mediapipe) (2.8.2)\n",
      "Requirement already satisfied: pycparser in c:\\programdata\\anaconda3\\lib\\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)\n",
      "Requirement already satisfied: six>=1.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install mediapipe --user"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33dd60fd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python311\\site-packages\\google\\protobuf\\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.\n",
      "  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '\n"
     ]
    }
   ],
   "source": [
    "# Initialize deques to store points for different colors\n",
    "bpoints = [deque(maxlen=1024)]  # Blue points\n",
    "gpoints = [deque(maxlen=1024)]  # Green points\n",
    "rpoints = [deque(maxlen=1024)]  # Red points\n",
    "ypoints = [deque(maxlen=1024)]  # Yellow points\n",
    "\n",
    "# Indexes to keep track of points in different color arrays\n",
    "blue_index = 0\n",
    "green_index = 0\n",
    "red_index = 0\n",
    "yellow_index = 0\n",
    "\n",
    "# Kernel for image dilation\n",
    "kernel = np.ones((5, 5), np.uint8)\n",
    "\n",
    "# List of colors in BGR format\n",
    "colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (0, 255, 255)]\n",
    "colorIndex = 0  # Default color index\n",
    "\n",
    "# Set up the canvas window with color buttons\n",
    "paintWindow = np.zeros((471, 636, 3)) + 255  # White canvas\n",
    "paintWindow = cv2.rectangle(paintWindow, (40, 1), (140, 65), (0, 0, 0), 2)  # Clear button\n",
    "paintWindow = cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), 2)  # Blue button\n",
    "paintWindow = cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), 2)  # Green button\n",
    "paintWindow = cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), 2)  # Red button\n",
    "paintWindow = cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), 2)  # Yellow button\n",
    "\n",
    "# Adding text labels on the canvas buttons\n",
    "cv2.putText(paintWindow, \"CLEAR\", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "cv2.putText(paintWindow, \"BLUE\", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "cv2.putText(paintWindow, \"GREEN\", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "cv2.putText(paintWindow, \"RED\", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "cv2.putText(paintWindow, \"YELLOW\", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "\n",
    "# Creating a window named 'Paint'\n",
    "cv2.namedWindow('Paint', cv2.WINDOW_AUTOSIZE)\n",
    "\n",
    "# Initialize Mediapipe for hand tracking\n",
    "mpHands = mp.solutions.hands\n",
    "hands = mpHands.Hands(max_num_hands=1, min_detection_confidence=0.7)\n",
    "mpDraw = mp.solutions.drawing_utils  # Utility for drawing hand landmarks\n",
    "\n",
    "# Initialize the webcam\n",
    "cap = cv2.VideoCapture(0)\n",
    "ret = True\n",
    "while ret:\n",
    "    # Read each frame from the webcam\n",
    "    ret, frame = cap.read()\n",
    "\n",
    "    x, y, c = frame.shape\n",
    "\n",
    "    # Flip the frame horizontally for natural (mirror-like) interaction\n",
    "    frame = cv2.flip(frame, 1)\n",
    "    \n",
    "    # Convert the frame from BGR to RGB\n",
    "    framergb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    # Draw color buttons on the frame\n",
    "    frame = cv2.rectangle(frame, (40, 1), (140, 65), (0, 0, 0), 2)\n",
    "    frame = cv2.rectangle(frame, (160, 1), (255, 65), (255, 0, 0), 2)\n",
    "    frame = cv2.rectangle(frame, (275, 1), (370, 65), (0, 255, 0), 2)\n",
    "    frame = cv2.rectangle(frame, (390, 1), (485, 65), (0, 0, 255), 2)\n",
    "    frame = cv2.rectangle(frame, (505, 1), (600, 65), (0, 255, 255), 2)\n",
    "    cv2.putText(frame, \"CLEAR\", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "    cv2.putText(frame, \"BLUE\", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "    cv2.putText(frame, \"GREEN\", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "    cv2.putText(frame, \"RED\", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "    cv2.putText(frame, \"YELLOW\", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)\n",
    "    \n",
    "    # Get hand landmark predictions\n",
    "    result = hands.process(framergb)\n",
    "\n",
    "    # Post-process the result\n",
    "    if result.multi_hand_landmarks:\n",
    "        landmarks = []\n",
    "        for handslms in result.multi_hand_landmarks:\n",
    "            for lm in handslms.landmark:\n",
    "                # Convert normalized coordinates to pixel coordinates\n",
    "                lmx = int(lm.x * 640)\n",
    "                lmy = int(lm.y * 480)\n",
    "                landmarks.append([lmx, lmy])\n",
    "\n",
    "            # Draw hand landmarks on the frame\n",
    "            mpDraw.draw_landmarks(frame, handslms, mpHands.HAND_CONNECTIONS)\n",
    "        \n",
    "        # Get coordinates of the forefinger and thumb\n",
    "        fore_finger = (landmarks[8][0], landmarks[8][1])\n",
    "        center = fore_finger\n",
    "        thumb = (landmarks[4][0], landmarks[4][1])\n",
    "        cv2.circle(frame, center, 3, (0, 255, 0), -1)  # Draw a circle at the tip of the forefinger\n",
    "        \n",
    "        # Check if thumb and forefinger are close to each other (indicating a click)\n",
    "        if (thumb[1] - center[1] < 30):\n",
    "            # Append new deque for each color to start a new line segment\n",
    "            bpoints.append(deque(maxlen=512))\n",
    "            blue_index += 1\n",
    "            gpoints.append(deque(maxlen=512))\n",
    "            green_index += 1\n",
    "            rpoints.append(deque(maxlen=512))\n",
    "            red_index += 1\n",
    "            ypoints.append(deque(maxlen=512))\n",
    "            yellow_index += 1\n",
    "\n",
    "        # Check if the forefinger is within the top button area (for clearing or color selection)\n",
    "        elif center[1] <= 65:\n",
    "            if 40 <= center[0] <= 140:  # Clear Button\n",
    "                # Reset all points and indexes\n",
    "                bpoints = [deque(maxlen=512)]\n",
    "                gpoints = [deque(maxlen=512)]\n",
    "                rpoints = [deque(maxlen=512)]\n",
    "                ypoints = [deque(maxlen=512)]\n",
    "\n",
    "                blue_index = 0\n",
    "                green_index = 0\n",
    "                red_index = 0\n",
    "                yellow_index = 0\n",
    "\n",
    "                # Clear the paint window\n",
    "                paintWindow[67:, :, :] = 255\n",
    "            elif 160 <= center[0] <= 255:\n",
    "                colorIndex = 0  # Blue\n",
    "            elif 275 <= center[0] <= 370:\n",
    "                colorIndex = 1  # Green\n",
    "            elif 390 <= center[0] <= 485:\n",
    "                colorIndex = 2  # Red\n",
    "            elif 505 <= center[0] <= 600:\n",
    "                colorIndex = 3  # Yellow\n",
    "        else:\n",
    "            # Append points to the corresponding deque based on selected color\n",
    "            if colorIndex == 0:\n",
    "                bpoints[blue_index].appendleft(center)\n",
    "            elif colorIndex == 1:\n",
    "                gpoints[green_index].appendleft(center)\n",
    "            elif colorIndex == 2:\n",
    "                rpoints[red_index].appendleft(center)\n",
    "            elif colorIndex == 3:\n",
    "                ypoints[yellow_index].appendleft(center)\n",
    "    else:\n",
    "        # Append new deque for each color to avoid messing up when no hand is detected\n",
    "        bpoints.append(deque(maxlen=512))\n",
    "        blue_index += 1\n",
    "        gpoints.append(deque(maxlen=512))\n",
    "        green_index += 1\n",
    "        rpoints.append(deque(maxlen=512))\n",
    "        red_index += 1\n",
    "        ypoints.append(deque(maxlen=512))\n",
    "        yellow_index += 1\n",
    "\n",
    "    # Draw lines of all the colors on the canvas and frame\n",
    "    points = [bpoints, gpoints, rpoints, ypoints]\n",
    "    for i in range(len(points)):\n",
    "        for j in range(len(points[i])):\n",
    "            for k in range(1, len(points[i][j])):\n",
    "                if points[i][j][k - 1] is None or points[i][j][k] is None:\n",
    "                    continue\n",
    "                # Draw lines on the frame\n",
    "                cv2.line(frame, points[i][j][k - 1], points[i][j][k], colors[i], 2)\n",
    "                # Draw lines on the paint window\n",
    "                cv2.line(paintWindow, points[i][j][k - 1], points[i][j][k], colors[i], 2)\n",
    "\n",
    "    # Display the frame and paint window\n",
    "    cv2.imshow(\"Output\", frame)\n",
    "    cv2.imshow(\"Paint\", paintWindow)\n",
    "\n",
    "    # Break the loop if 'q' key is pressed\n",
    "    if cv2.waitKey(1) == ord('q'):\n",
    "        break\n",
    "\n",
    "# Release the webcam and destroy all active windows\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab8b69cd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0ab7485",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62599c42",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
